name: Release

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@master
        with:
          go-version: 1.23
      - uses: golangci/golangci-lint-action@v6
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@master
        with:
          go-version: 1.23
      - run: go test -v ./...
  release:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@master
        with:
          go-version: 1.23
      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
